name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger:xunit /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: Tests/TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
